name: Develop-Premerge

on:
  pull_request:
    branches:
      - develop

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          JENKINS_CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          curl -X POST "$JENKINS_URL/job/hello-world-ui-premerge/build" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -H "$JENKINS_CRUMB"
